/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if libupnp is available */
/* #undef HAVE_LIBUPNP */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* package name */
#define PACKAGE "gmediarender"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://gmrender.nongnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "gmediarender"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "gmediarender 0.0.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gmediarender"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.6"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* package version */
#define VERSION "0.0.6"

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */
